### ISSUE TITLE
Esta regla no debería ser necesaria

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#1]
https://github.com/alexmclm/pdep2020TP/blob/ec3074b3dca8ac66327168fbb0c6da88b56e4c20/tp1.hs#L2

Qué te tira si comentás esta linea?

**Comment by alexmclm** [comment]
el programa sigue funcionando igual jajaja, el tema nomas es que la cursada anterior habia probado los test para haskell y mi compañero del grupo me habia pasado esa regla y todas las demas, yo solo hice copy paste de eso jajaaj

**Comment by natoszme** [comment]
Nop definitivamente no la quermos :)

La querés sacar? Una vez que lo hayas hecho, podés cerrar este issue así no se acumulan
