### ISSUE TITLE
Se podría buscar un mejor nombre relacionado a la subasta

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#11]
https://github.com/alexmclm/pdep2020TP/blob/09a30dd31aee16b6be01f1678834a51daa85b34c/tp1.hs#L60

Porque así quedó medio genérico

**Comment by alexmclm** [comment]
soy medio malo aveces con los nombres jajajaa o suelen ser muy largos a tal punto de ser realmente descriptivo o ser cortos y ser medio medio ajajaja.
le parece bien un nombre como esTacticaOferenteOAccionista ?

**Comment by natoszme** [comment]
podria ser un buen nombre, si!
