### ISSUE TITLE
alquileresAcobrar se puede mejorar

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#12]
https://github.com/alexmclm/pdep2020TP/blob/09a30dd31aee16b6be01f1678834a51daa85b34c/tp1.hs#L72

Teniendo en cuenta que está repetida la lógica filtrar las propiedades baratas/caras
`(length.filter esPropiedadBarata) unaPropiedad`
y después multiplicar por un número.

Qué opinás de hacer algo así?

```
precioAlquiler :: Propiedad -> Int
precioAlquiler propiedad =
    | esPropiedadBarata propiedad = 10
    | otherwise = 20

alquileresAcobrar :: Persona -> Int
alquileresAcobrar unaPersona = (sum . map precioAlquiler . propiedades) unaPersona
```

Lo ves mejor? Peor? Más difícil? Contame

**Comment by alexmclm** [comment]
la veo un poco confusa ...bah no confusa , debido a que deberia devolver un (*10) o (*20), tal vez fue un error jajaja, pero si, lo llegue a entender esa parte
creo que lo capte

**Comment by natoszme** [comment]
En esta solución no hay que ir multiplicando *10 o *20 por cada propiedad, sino que calculamos el valor asociado a cada propiedad (10 o 20) y al final los sumamos.

Te sugiero intentar implementarla!
