### ISSUE TITLE
Debería devolver al ganador después de haber jugado la última ronda

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#14]
https://github.com/alexmclm/pdep2020TP/blob/09a30dd31aee16b6be01f1678834a51daa85b34c/tp1.hs#L107

Por ahora lo estamos devolviendo sin tener en cuenta que jugó todas sus acciones

**Comment by alexmclm** [comment]
si, precisamente es lo que hace, la funcion dineroTotal lo que hace es devolverme el monto fijo luego de haber realizado las acciones, que se hizo luego de haber sido "foldldeadas" (por asi decirlo jajaaj), en el caso de carolina que tiene inicialmente 500 de dinero
y tiene accion de pagarAAccionistas, que hace le reste 100 por que tiene una habilidad de ser accionista, tenga 400 en dinero 
entonces al hacer esto, comparo dinero total de una persona con la de otra y devolverme la persona mas adinerada , en caso contrario, la otra

**Comment by alexmclm** [comment]
ya entendi lo que quisiste decir jajaaj. que devuelva a la persona ganadora ya "modificada" , no?

**Comment by natoszme** [comment]
Tal cual! Que devuelva a la persona nueva con el estado después de haber jugado :+1:
