### ISSUE TITLE
Poner las condiciones en el renglón de abajo de la definición de la función

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#15]
https://github.com/alexmclm/pdep2020TP/blob/09a30dd31aee16b6be01f1678834a51daa85b34c/tp1.hs#L85

Como vimos en clase :)

**Comment by alexmclm** [comment]
jajajaja, siempre me olvido, costumbre

**Comment by natoszme** [comment]
Cuando puedas ajustá y cerrá el issue :100:
