### ISSUE TITLE
aumentarDineral y restarDineral son muy parecidas

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#16]
https://github.com/alexmclm/pdep2020TP/blob/09a30dd31aee16b6be01f1678834a51daa85b34c/tp1.hs#L34

Y si además de `unDinero` parametrizamos la operación (suma o resta)?
Esto nos permitiría tener una única función a la que además del dinero, le pasamos `(+)` o `(-)`

**Comment by alexmclm** [comment]
esooo jajajaja, te juro que en este caso tengo un pequeño problema a la hora de querer parametrizar esto , osea me chillaba debido a que es un solo signo pero por ese signo hace que no me funcione jajaja. ahora mañana miro el codigo, hago un intento y veo si lo puedo solucionar jjaja
