### ISSUE TITLE
hacerBerrinchePor no funciona

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#17]
https://github.com/alexmclm/pdep2020TP/blob/09a30dd31aee16b6be01f1678834a51daa85b34c/tp1.hs#L91

Lo que faltaría para que funque es... (complete aquí)

¿Qué debería pasar si no le alcanza la plata?

**Comment by alexmclm** [comment]
el otherwise puede ser?, la habia definido abajo jajaaj

**Comment by natoszme** [comment]
Nop, lo que decía es que entra una vez, y si no le alcanza la plata devuelve a la misma persona. Lo que queremos es que siga intentando `hacerBerrinchePor`, por lo que en ese caso debería llamarse recursivamente

Si no se entiende, podemos hacer una llamada y aclaramos este y el resto de los issues pendientes. Avisame!

**Comment by alexmclm** [comment]
ehhhh, osea que no terminaria mas la funcion hacerBerrinche ...puede ser?
hacerBerrinchePor unaPropiedad unaPersona
 | alcanzaDinero unaPropiedad unaPersona  = comprarPropiedad unaPropiedad unaPersona
 | otherwise  = hacerBerrinchePor unaPropiedad unaPersona

**Comment by natoszme** [comment]
No! Si termina, cuando le alcanzaDinero ;)

**Comment by alexmclm** [comment]
entonces puede ser asi la funcion?
hacerBerrinchePor unaPropiedad unaPersona
 | alcanzaDinero unaPropiedad unaPersona  = comprarPropiedad unaPropiedad unaPersona
 | otherwise  = ((hacerBerrinchePor unaPropiedad). modificarDinero (+10)) unaPersona
jajaja

**Comment by natoszme** [comment]
Casi perfecto! Lo que faltaria cambiar es que en comprarPropiedad solo tiene que agregar la propiedad y disminuir su dinero, no tiene que gritar. La parte de gritar hay que moverla a donde tenes la parte que aumenta el dinero en 10.
Y donde ahora se llama a gritar (en comprarPropiedad), hay que disminuir el dinero!

Tas muy cerquita!
