### ISSUE TITLE
No definir odioDe(tiaAgatha, _) a mano

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#18]
https://github.com/alexmclm/pdep2020TP/blob/0c6bf44a9afe5ac07bc6fb5bef03081f76c43848/tpClase1.pl#L6

Sino que hacerlo usando reglas. Sino, qué pasa si se agrega más gente que vive en la mansión?

**Comment by alexmclm** [comment]
ya lo arregle este punto jajaja
