### ISSUE TITLE
Hace falta generar en matoA?

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#19]
https://github.com/alexmclm/pdep2020TP/blob/0c6bf44a9afe5ac07bc6fb5bef03081f76c43848/tpClase1.pl#L21

`odioDe/2` ya está generando!

**También, revisar todas las otras generaciones que hiciste en base a los requerimientos del punto 2 del enunciado**

**Comment by alexmclm** [comment]
ya lo entendi jajajaaj, ahi mande de vuetla el codigo arreglado. disculpe la demora
