### ISSUE TITLE
Ya que tenemos definidos los otros setters, podrías también usar uno para cambiar el nombre

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#2]
https://github.com/alexmclm/pdep2020TP/blob/ec3074b3dca8ac66327168fbb0c6da88b56e4c20/tp1.hs#L46

Para manejar la misma forma de cambiar el nombre que el dinero por ejemplo (o sea, una función a la que le pasas el nombre y te lo cambia)

**Comment by alexmclm** [comment]
arreglado
