### ISSUE TITLE
Si delegás la primer condición, podés aprovechar pattern matching

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#5]
https://github.com/alexmclm/pdep2020TP/blob/ec3074b3dca8ac66327168fbb0c6da88b56e4c20/tp1.hs#L54

Usando alguna función como esTacticaGanadora, que recibe la táctica y da true sólo para estas dos

**Comment by alexmclm** [comment]
creo que lo termine haciendo, esta bien¿

**Comment by natoszme** [comment]
Ta mejor!

Pero no se está usando pattern matching todavía. Se te ocurre cómo agregarlo acá?

https://github.com/alexmclm/pdep2020TP/blob/3b21ac32fe4431b68e1ee599cd5aae070856a562/tp1.hs#L52
